Added README for andino_bringup
Ekumen-OS/andino pull request #233
Opened 2024-03-26 09:17 UTC by JesusSilvaUtrera

# 🎉 New feature

Closes #146 

## Summary
I have added the README.md file to the `andino_bringup` package, explaining the contents of the package.

## Test it
You can check the file and read it to see if it is complete.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-03-26 12:58 UTC, jballoffet requested changes
Thanks @JesusSilvaUtrera! I left some minor comments, PTAL.

2024-03-26 12:58 UTC, jballoffet commented on andino_bringup/README.md
> +These launch files are included just in case we want to command the robot in different ways, or visualize the information:
nit: "... in case you want ..."

2024-03-26 12:58 UTC, jballoffet commented on andino_bringup/README.md
> +- `rviz.launch.py`: executes the RViz visualization tool with the 'andino.rviz' configuration by default, to be able to visualize the 3D model of the robot and information form the topics.
typo: "from the topics"

2024-03-26 12:58 UTC, jballoffet commented on andino_bringup/README.md
> +- `andino_control.launch.py`: file for the ROS2 control nodes and drivers.
nit: "ROS 2 control" or `ros2_control`.

2024-03-27 11:13 UTC, JesusSilvaUtrera commented
@jballoffet I have updated the README and the branch, if you think it is good we can merge it.

2024-03-27 12:20 UTC, jballoffet approved these changes
LGTM, thanks for contributing to Andino!

2024-03-27 12:20 UTC, merged

2024-03-27 13:07 UTC, francocipollone reviewed
Thanks!