Include robot assembly
Ekumen-OS/andino pull request #238
Opened 2024-04-26 12:48 UTC by JesusSilvaUtrera

# 🎉 New feature

Closes #237 

## Summary
I have added to the `README.md` of the `andino_hardware` package the assembly steps.

## Test it
Just check the `README.md`

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: I will open the PR as a draft first to discuss what things to add, or whether the format is okay or not.

2024-04-30 13:09 UTC, francocipollone requested changes
Looking good! Just dropped some comments :rocket:

2024-04-30 13:09 UTC, francocipollone commented on andino_hardware/README.md
> +<img src="docs/Parts.jpg">
You can add this as first step: 1. Gather all parts together
Add also a note here stating that the printed encoder wheels are not necessary.

2024-04-30 13:09 UTC, francocipollone commented on andino_hardware/README.md
> +  <img src="docs/Caster_wheel_H_bridge.jpg">
let's standarize the name of the files to be all snake_case

2024-04-30 13:09 UTC, francocipollone commented on andino_hardware/README.md
> +  Here you have a front image of how the idler wheel are mounted to the chassis:
let's use caster instead of idler

2024-04-30 19:13 UTC, francocipollone approved these changes

2024-04-30 19:13 UTC, francocipollone commented on andino_hardware/README.md
> +The steps to reproduce the mounting of the Andino are:
Being super obnoxious (nit ^10) :nerd_face:  : I guess we can remove this line as the section and steps are self explanatory

2024-05-01 21:19 UTC, francocipollone reviewed
Just noticed the following: the size of the images.

In order to avoid having a heavyweight repo, could you try to compress the images even more? I think that having images up to 1mb would be enough. (in case we notice the quality is too bad we could be stretch up to 2mb).

2024-05-01 21:19 UTC, francocipollone commented on andino_hardware/docs/parts.png
Wow 26 mb.

2024-05-01 21:19 UTC, francocipollone commented on andino_hardware/docs/parts.png
Btw I love the numbers for guiding.

2024-05-01 21:24 UTC, JesusSilvaUtrera commented on andino_hardware/docs/parts.png
Yeah I thought about it this morning too, I will do that tomorrow, let's see if the image with the numbers can be compressed uo to 2 mb and look good, with the others there shouldn't be any problem.

2024-05-01 21:26 UTC, JesusSilvaUtrera commented on andino_hardware/docs/parts.png
By the way, do you know which tool was used for the connections diagram? I was thinking of using GIMP to create it but just for curiosity.

2024-05-02 11:13 UTC, francocipollone commented on andino_hardware/docs/parts.png
Super handmade. Check this: https://docs.google.com/drawings/d/1wummJPj3EJHSpB-iakCe97DVVQHOPI6oLSaNHQ7MesI/edit

2024-05-02 11:18 UTC, JesusSilvaUtrera commented on andino_hardware/docs/parts.png
Great, thanks!

2024-06-09 23:27 UTC, francocipollone commented
Just passing by, I haven't reviewed as it is a draft, let me know otherwise :+1:

2024-09-11 12:14 UTC, JesusSilvaUtrera commented
@francocipollone @jballoffet this PR is ready for review, I have added the photo of the completed assembly. I know there are some problems with DCO from long ago and I noticed now, but I tried to do the rebase and they are a lot of commits to solve conflicts, so in the meantime you can take a look at the PR to give feedback if there is anything else you'd like to introduce, so we have time before RosCon.

Thanks in advance to both!

2024-09-13 08:32 UTC, JesusSilvaUtrera commented
closing as there are too many conflicts to rebase, I will open a new fresh PR with all the final changes, so it's easier to review.

2024-09-13 08:32 UTC, closed without merging