Add new Arduino diagram
Ekumen-OS/andino pull request #249
Opened 2024-05-15 09:46 UTC by JesusSilvaUtrera

# 🎉 New feature

Part of #239 

## Summary
This PR is just to add the new diagram for the Arduino Nano, motors and IMU with the changes from the firmware, in order to delete the warning on the `README.md` in `andino_hardware` package.

Just FYI @jballoffet: I didn't replace the 5V and GND for their electric symbols becuase when I tried it, the symbols had to be really small and I think at the end the diagram became less clear.

## Test it

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-05-15 10:09 UTC, jballoffet commented on andino_description/test/__pycache__/test_xacro_processing.cpython-310-pytest-6.2.5.pyc
This file shouldn't be part of this PR, right?

2024-05-15 10:12 UTC, jballoffet commented on andino_hardware/docs/andino_diagram_arduino.jpg
These connections are missing: https://github.com/Ekumen-OS/andino/blob/humble/andino_firmware/src/hw.h#L46-L62, please fix.

2024-05-15 12:50 UTC, JesusSilvaUtrera commented on andino_description/test/__pycache__/test_xacro_processing.cpython-310-pytest-6.2.5.pyc
Yeah it must have stayed from another branch

2024-05-16 03:11 UTC, francocipollone reviewed
Thanks for the changes, this is super useful.
+1 to Javi's comments.

I wonder if it makes sense to also integrate here the stepup regulator.

2024-05-16 05:45 UTC, JesusSilvaUtrera commented
> I wonder if it makes sense to also integrate here the stepup regulator.

I was thinking of doing 3 diagrams: this one for the arduino, another one for the Raspberry Pi and the final one for the power, so the stepup would be placed there.

2024-05-16 09:58 UTC, jballoffet commented on andino_hardware/docs/andino_diagram_arduino.jpg
I've just noticed that either the right motor or the left motor connection is reversed, e.g. "Motor Driver - Pin 1" seems to be the first pin (from left to right with the green pcb below) on the left motor, but instead the last one on the right motor. We should either modify the connections or mirror the motor image.

2024-05-16 09:59 UTC, jballoffet requested changes
Thanks @JesusSilvaUtrera! Left some comments, PTAL.

2024-05-16 10:32 UTC, JesusSilvaUtrera commented on andino_hardware/docs/andino_diagram_arduino.jpg
You are right, it has taken me a while to see which one was wrong but now I see that the left motor should be reverted.

2024-05-16 10:40 UTC, JesusSilvaUtrera commented on andino_hardware/docs/andino_diagram_arduino.jpg
Now I am also wondering if the `Motro Driver - Pin 1` of the left motor should be connected to Out3 or Out4, because maybe I am connecting that also reversed and the motor will turn the other way.

2024-05-16 10:49 UTC, JesusSilvaUtrera commented on andino_hardware/docs/andino_diagram_arduino.jpg
I am a bit confused because in some photos they seem to be reverted and in others don't, so I will leave it like that for now and see what you think.

2024-05-16 14:01 UTC, jballoffet commented on andino_hardware/docs/andino_diagram_arduino.jpg
Yes, it is hard to know in advance indeed. I suggest we keep it as is and then assemble it exactly as described on the diagram (and fix it if needed).

2024-05-16 14:01 UTC, jballoffet approved these changes
LGTM, thanks @JesusSilvaUtrera!

2024-05-16 14:01 UTC, merged