Update connections diagram
Ekumen-OS/andino pull request #252
Opened 2024-05-27 06:35 UTC by JesusSilvaUtrera

# 🎉 New feature

Closes #239 

## Summary
I have updated the Arduino diagram with the new voltages for the power, and I added the Raspberry diagram, which also includes the step-up and the IMU connections. It is in the `andino_hardware/README.md` file.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-05-27 07:52 UTC, jballoffet commented on andino_hardware/README.md
Let's move diagram notes to the markdown file so as to make it easier to maintain them afterwards.

2024-05-27 07:52 UTC, jballoffet requested changes
Thanks @JesusSilvaUtrera! I left one comment, PTAL.

2024-05-27 10:19 UTC, jballoffet commented on andino_hardware/docs/andino_diagram_raspberry.jpg
Is it required to connect the input and output GND pins of the DC-DC step up?

2024-05-27 10:19 UTC, jballoffet requested changes
Thanks! I left some more comments, PTAL.

2024-05-27 13:29 UTC, JesusSilvaUtrera commented on andino_hardware/docs/andino_diagram_raspberry.jpg
Actually, I am not sure, I will research a bit.

2024-05-27 13:38 UTC, JesusSilvaUtrera commented on andino_hardware/docs/andino_diagram_raspberry.jpg
It seems so, because the important part is the voltage difference between the + and - IN, and also to close the circuit. If you leave that disconnected, the circuit will be opened and, therefore, no current or voltage will be generated. At least that's what I think and have seen in some connection examples.

2024-05-27 16:09 UTC, jballoffet commented on andino_hardware/README.md
> +*NOTE: depending on how good is the powerbank we have, the motors should be powered with more or less voltage. While a higher voltage value (up to 9V) leads to smoother operation (better motor speed
What about `depending on the power bank maximum output current, the motors may need to be powered with a voltage value less than 9V. While a higher...`?

2024-05-27 16:10 UTC, jballoffet requested changes
Left one comment, PTAL. Thanks!

2024-05-28 07:10 UTC, jballoffet commented on andino_hardware/docs/andino_diagram_raspberry.jpg
Ack, thank you!

2024-05-28 07:11 UTC, jballoffet approved these changes
LGTM, thanks @JesusSilvaUtrera!

2024-05-28 07:11 UTC, merged